blank_issues_enabled: false
contact_links:
  - name: Get help
    url: https://github.com/mmaachado/template/issues
    about: Something is not working the way you expected and you are not sure it is a bug.
